// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace stockAppApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230725091922_transactiontable")]
    partial class transactiontable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("stockAppApi.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Date")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("TEXT")
                        .HasColumnName("MarketCap");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal?>("PERatio")
                        .HasColumnType("TEXT")
                        .HasColumnName("PERatio");

                    b.Property<decimal?>("PercentageChange")
                        .HasColumnType("TEXT")
                        .HasColumnName("PercentageChange");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<decimal?>("ShareFloat")
                        .HasColumnType("TEXT")
                        .HasColumnName("ShareFloat");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("Symbol");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("TEXT")
                        .HasColumnName("Volume");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("stockAppApi.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("StockId")
                        .HasColumnType("TEXT")
                        .HasColumnName("StockId");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
