# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  stockappapi:
    image: stockappapi
    build:
      context: .
      dockerfile: stockAppApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5097:5097
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
